### ISSUE TITLE
GraphQL Demo {"message":"Missing Authentication Token"}

### ISSUE THREAD

**Issue by bdougie** [kevinold/serverless-tutorial-fluentconf-2017#2]
I am attempting to finishing exploring the examples you went through at Fluent Conf and getting a missing auth token error when attempting to hit graphQL enpoints. Its the same in browser as it is in GraphiQL.
```sh
curl https://43l2w6idi8.execute-api.us-east-1.amazonaws.com/dev/graphql
> {"message":"Missing Authentication Token"}
```
Is this correct and what auth do I put in the header?

![screenshot 2017-07-04 02 44 37](https://user-images.githubusercontent.com/5713670/27824887-bdf376cc-6062-11e7-9851-ba75116e7953.png)

```sh
START RequestId: 6208b8e5-609d-11e7-83c1-537764d73e7f Version: $LATEST
module initialization error: ReferenceError
    at __webpack_require__ (/var/task/handler.js:20:30)
    at Object.defineProperty.value (/var/task/handler.js:40:18)
    at Object.<anonymous> (/var/task/handler.js:43:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
END RequestId: 6208b8e5-609d-11e7-83c1-537764d73e7f
REPORT RequestId: 6208b8e5-609d-11e7-83c1-537764d73e7f	Duration: 2.90 ms	Billed Duration: 100 ms 	Memory Size: 1024 MB	Max Memory Used: 30 MB	
```

**Comment by kevinold** [comment]
Odd, I've had this happen from time to time with serverless-webpack rolled projects.  I worked from the same repos during the training.  I'll see if I can find the difference.

**Comment by kevinold** [comment]
I just verified that I have the same code as what's pushed up and that service deployed here still works:

https://i2la4hb02l.execute-api.us-east-1.amazonaws.com/dev/graphql

**Comment by kevinold** [comment]
There could be the chance that it's error without good debugging info.

Did you run the load-jokes script to populate your table with data?

**Comment by bdougie** [comment]
I haven't had time till now to this again. I don't think I ran the load jokes script, but have now and get an empty object.

![screenshot 2017-07-20 20 12 40](https://user-images.githubusercontent.com/5713670/28447759-d0062940-6d87-11e7-94e5-30c938be4aa0.png)

I have actually built a GraphQL wrapper for work and going to attempt to migrate it to lambda soon
